site:
  about:
    siteName: Neebt
    siteDescription: Kotlin library to work with the NBT file format.
Editorial:
  primaryColor: '#674876'
  legacySearch: false
  social:
    github: 'nee/neebt'
  metaComponents: # this is the replacement for the deprecated automatic search addition
    - type: 'orchidSearch'
  menu:
    - type: 'separator'
      title: 'Wiki'
    - type: 'wiki'
    - type: 'page'
      itemId: 'Changelog'
    - type: 'separator'
      title: 'API Docs'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'

kotlindoc:
  sourceDirs:
    - './../../../../src/main/kotlin'
  sourcePages:
    menu:
      - type: 'sourcedocPageLinks'
        moduleType: 'kotlindoc'
        itemTitleType: 'SIGNATURE'
        includeItems: true

services:
  publications:
    stages:
      - type: 'githubPages'
        username: 'LeonardNolting'
        repo: 'nee/neebt'
      - type: 'githubReleases'
        repo: 'nee/neebt'